import React, { useState } from "react";
import axios from "axios";
import styles from "@/styles/register.module.css";
import Link from "next/link";
import Head from "next/head";
import swal from 'sweetalert';
import { useRouter } from "next/router";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";



function Register() {
  const router = useRouter();
 

  const [formData, setFormData] = useState({
    name: "",
    email: "",
    phone: "",
    password: "",
    confirmpassword: "",
    jabatan: "",
    nama_perusahaan:"",
    role: "pekerja",
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prevFormData) => ({ ...prevFormData, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
  
    try {
      const { role, ...data } = formData;
  
      if (role === "pekerja") {
        delete data.jabatan;
        delete data.nama_perusahaan;
      }
  
      await axios.post(`${process.env.NEXT_PUBLIC_REACT_APP_API_KEY}/users/register/${role}`, data);
      toast.success("Sign Up Success, Please check your email for verification");
      setTimeout(() => {
        router.push(`/auth/login`);
      }, 3000); 
    } catch (error) {
      const errorMessage = error.response?.data?.message || "Unknown error occurred";
      toast.error( `Registration failed: ${errorMessage}`);
      console.log(error)
      
    }
  };

  const handleRoleClick = (selectedRole) => {
    setFormData((prevFormData) => ({
      ...prevFormData,
      role: selectedRole,
    }));
  };
  
  return (
    <>
      <Head>
        <title>Peworld</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <style>
        {`
       .nav-pills .nav-link.active {
         color: #fff;
         background-color: #fbb017;
       }
        
        `}
      </style>
      <ToastContainer />
      <div className={styles["half-screen-container"]}>
        <div className={styles["half-screen-image"]}>
          <div className={styles.overlay} />
          <img className={styles.icon} src="/peworld.png" alt="" />
          <h1 className={styles.title}>
            Temukan developer berbakat &amp; terbaik di berbagai bidang keahlian
          </h1>
        </div>
        <div className={styles.content}>
          <div className={`${styles["form-title"]}`}>
            <h1>Daftar</h1>
          </div>
          <div className="button-link mt-3 ">
            <ul
              className={`nav nav-pills mb-3 justify-content-center`}
              id="pills-tab"
              role="tablist"
            >
              <li className="nav-item" role="presentation">
                <button
                  className="nav-link active b"
                  id="pills-home-tab"
                  data-toggle="pill"
                  data-target="#pills-home"
                  type="button"
                  role="tab"
                  aria-controls="pills-home"
                  aria-selected="true"
                  onClick={() => handleRoleClick("pekerja")} 
                >
                  Pekerja
                </button>
              </li>
              <li className="nav-item" role="presentation">
                <button
                  className="nav-link"
                  id="pills-profile-tab"
                  data-toggle="pill"
                  data-target="#pills-profile"
                  type="button"
                  role="tab"
                  aria-controls="pills-profile"
                  aria-selected="false"
                  onClick={() => handleRoleClick("perekrut")} 
                >
                  Perekrut
                </button>
              </li>
            </ul>
          </div>
          <div className="container">
            <div className="tab-content " id="pills-tabContent">
              <div
                className={`tab-pane fade show active`}
                id="pills-home"
                role="tabpanel"
                aria-labelledby="pills-home-tab"
              >
                <form onSubmit={handleSubmit}>
                  <div className={`${styles["form-group-input"]}`}>
                    <span>Nama</span>
                    <input
                      name="name"
                      className={`form-control`}
                      placeholder="Masukan nama panjang"
                      type="nama"
                      value={formData.name}
                      onChange={handleChange}
                    />
                  </div>
                  <div className={`${styles["form-group-input"]}`}>
                    <span>Email</span>
                    <input
                      name="email"
                      className={`form-control`}
                      placeholder="Masukan alamat email"
                      type="email"
                      value={formData.email}
                      onChange={handleChange}
                    />
                  </div>
                  <div className={`${styles["form-group-input"]}`}>
                    <span>No Handphone</span>
                    <input
                      name="phone"
                      className={`form-control`}
                      placeholder="Masukkan nomor handphone"
                      type="tel"
                      value={formData.phone}
                      onChange={handleChange}
                    />
                  </div>
                  <div className={`${styles["form-group-input"]}`}>
                    <span>Kata Sandi</span>
                    <input
                      name="password"
                      className={`form-control`}
                      placeholder="Masukan kata sandi"
                      type="password"
                      value={formData.password}
                      onChange={handleChange}
                    />
                  </div>
                  <div className={`${styles["form-group-input"]}`}>
                    <span>Konfirmasi kata sandi</span>
                    <input
                      name="confirmpassword"
                      className={`form-control`}
                      placeholder="Masukan konfirmasi kata sandi"
                      type="password"
                      value={formData.confirmpassword}
                      onChange={handleChange}
                    />
                  </div>
                  <div className={`${styles["form-group"]} pt-3`}>
                    <button
                      className={`${styles.btn} btn btn-block`}
                      type="submit"
                    >
                      Daftar
                    </button>
                    <h6 className="pt-3 text-center">
                      Anda sudah punya akun?{" "}
                      <Link href="/auth/login">Masuk disini</Link>
                    </h6>
                  </div>
                </form>
              </div>
              <div
                className={`tab-pane fade`}
                id="pills-profile"
                role="tabpanel"
                aria-labelledby="pills-profile-tab"
              >
                <form onSubmit={handleSubmit}>
                  <div className={`${styles["form-group-input"]}`}>
                    <span>Nama</span>
                    <input
                      name="name"
                      className={`form-control`}
                      placeholder="Masukan nama panjang"
                      type="text"
                      value={formData.name}
                      onChange={handleChange}
                    />
                  </div>
                  <div className={`${styles["form-group-input"]}`}>
                    <span>Email</span>
                    <input
                      name="email"
                      className={`form-control`}
                      placeholder="Masukan alamat email"
                      type="email"
                      value={formData.email}
                      onChange={handleChange}
                    />
                  </div>
                  <div className={`${styles["form-group-input"]}`}>
                    <span>Perusahaan</span>
                    <input
                      name="nama_perusahaan"
                      className={`form-control`}
                      placeholder="Masukan nama perusahaan"
                      type="text"
                      value={formData.nama_perusahaan}
                      onChange={handleChange}
                    />
                  </div>
                  <div className={`${styles["form-group-input"]}`}>
                    <span>Jabatan</span>
                    <input
                      name="jabatan"
                      className={`form-control`}
                      placeholder="Posisi di perusahaan Anda"
                      type="text"
                      value={formData.jabatan}
                      onChange={handleChange}
                    />
                  </div>
                  <div className={`${styles["form-group-input"]}`}>
                    <span>No Handphone</span>
                    <input
                      name="phone"
                      className={`form-control`}
                      placeholder="Masukkan nomor handphone"
                      type="tel"
                      value={formData.phone}
                      onChange={handleChange}
                    />
                  </div>
                  <div className={`${styles["form-group-input"]}`}>
                    <span>Kata Sandi</span>
                    <input
                      name="password"
                      className={`form-control`}
                      placeholder="Masukan kata sandi"
                      type="password"
                      value={formData.password}
                      onChange={handleChange}
                    />
                  </div>
                  <div className={`${styles["form-group-input"]}`}>
                    <span>Konfirmasi kata sandi</span>
                    <input
                      name="confirmpassword"
                      className={`form-control`}
                      placeholder="Masukan konfirmasi kata sandi"
                      type="password"
                      value={formData.confirmpassword}
                      onChange={handleChange}
                    />
                  </div>
                  <div className={`${styles["form-group"]} pt-3`}>
                    <button
                      className={`${styles.btn} btn btn-block`}
                      type="submit"
                    >
                      Daftar
                    </button>
                    <h6 className="pt-3 text-center">
                      Anda sudah punya akun?
                      <Link href="/auth/login">Masuk disini</Link>
                    </h6>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default Register;
