import Head from "next/head";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import NavbarLogin from "@/components/navbarLogin/Navbar";
import React, { useState, useEffect } from "react"; 
import Link from "next/link";
import Cookies from 'js-cookie';
function App() {
  const [isLoggedIn, setIsLoggedIn] = useState(false); 

  useEffect(() => {
    const token = Cookies.get('token') ;
    if (token) {
      setIsLoggedIn(true);
    }
  }, []);
  return (
    <>
      <Head>
        <title>Peworld</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        <link rel="icon" href="/icon.png" />
      </Head>
      {isLoggedIn ? <NavbarLogin /> : <Navbar />} 

      <section className="section1">
          <div className="container">
            <div className="row">
              {/* Left Section */}
              <div className="col-lg-6 col-md-12 left-section">
                <div className="text-container">
                  <span className="centered">Talenta terbaik negri</span>
                  <span className="centered">untuk perubahan</span>
                  <span className="centered">revolusi 4.0</span>
                </div>
                <p className="paragraph">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  <br />
                  In euismod ipsum et dui rhoncus auctor.
                </p>
                <Link href={"/auth/login"}>
                <button className="btn btn-mulai">Mulai Dari Sekarang</button>
                </Link>
              </div>
              {/* Right Section */}
              <div className="col-lg-6 col-md-12 p-0 m-0 right-section">
                <div className="image-container">
                  <div className="background-box1" />
                  <div className="background-box2" />
                  <div className="background-box3">
                    <img src="/Union.png" alt="" />
                  </div>
                  <img className="image-section" src="/Mask Group.png" alt="" />
                  <div className="background-overlay" />
                </div>
              </div>
            </div>
          </div>
      </section>
      <section className="section2">
          <div className="container">
            <div className="row">
              {/* Left Section */}
              <div className="col-lg-6 col-md-12 left-section">
                <div className="image-container">
                  <div className="background-box1" />
                  <img
                    className="image-section"
                    src="/Rectangle 519.png"
                    alt=""
                  />
                  <div className="background-overlay" />
                </div>
              </div>
              {/* Right Section */}
              <div className="col-lg-6 col-md-12 right-section">
                <h1>Kenapa harus mencari talent di peworld</h1>
                <div className="icon-text">
                  <i className="bi bi-check-circle-fill" />
                  <span>Lorem ipsum dolor sit amet.</span>
                </div>
                <div className="icon-text">
                  <i className="bi bi-check-circle-fill" />
                  <span>Lorem ipsum dolor sit amet.</span>
                </div>
                <div className="icon-text">
                  <i className="bi bi-check-circle-fill" />
                  <span>Lorem ipsum dolor sit amet.</span>
                </div>
                <div className="icon-text">
                  <i className="bi bi-check-circle-fill" />
                  <span>Lorem ipsum dolor sit amet.</span>
                </div>
              </div>
            </div>
          </div>
      </section>
      <section className="section3">
          <div className="container">
            <div className="row">
              {/* Left Section */}
              <div className="col-lg-6 left-section">
                <h1>Skill Talent</h1>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  <br />
                  In euismod ipsum et dui rhoncus auctor.
                </p>
                <div className="icon-text">
                  <i className="bi bi-check-circle-fill" />
                  <span>Java.</span>
                  <i className="bi bi-check-circle-fill" />
                  <span>Golang</span>
                </div>
                <div className="icon-text">
                  <i className="bi bi-check-circle-fill" />
                  <span>Kotlin.</span>
                  <i className="bi bi-check-circle-fill" />
                  <span>C++</span>
                </div>
                <div className="icon-text">
                  <i className="bi bi-check-circle-fill" />
                  <span>PHP.</span>
                  <i className="bi bi-check-circle-fill" />
                  <span>Ruby</span>
                </div>
                <div className="icon-text">
                  <i className="bi bi-check-circle-fill" />
                  <span>JavaScript.</span>
                  <i className="bi bi-check-circle-fill" />
                  <span>10+ Other Languages</span>
                </div>
              </div>
              {/* Right Section */}
              <div className="col-lg-6 right-section">
                <div className="image-container">
                  <div className="background-box1" />
                  <img src="/Rectangle 519_2.png" alt="" />
                  <div className="background-overlay" />
                </div>
              </div>
            </div>
          </div>
      </section>
      <section className="section4" id="section4">
          <div className="container mt-4">
            <h1 className="text-center pb-5">Their opinion about peworld</h1>
            <div
              id="myCarousel"
              className="carousel slide"
              data-ride="carousel"
            >
              <div className="carousel-inner">
                <div className="carousel-item active">
                  <div className="row">
                    <div className="col-lg-4 col-md-6">
                      <div className="card">
                        <img
                          src="/Ellipse 320.png"
                          className="card-img-top"
                          alt="Card Image 1"
                        />
                        <div className="card-body">
                          <h2 className="card-title">Harry Styles</h2>
                          <p className="card-job">Web Developer</p>
                          <p className="card-text">
                            Lorem ipsum dolor sit amet, consectetur adipiscing
                            elit. In euismod ipsum et dui rhoncus auctor.
                          </p>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-4 col-md-6">
                      <div className="card">
                        <img
                          src="/Ellipse 323.png"
                          className="card-img-top"
                          alt="Card Image 2"
                        />
                        <div className="card-body">
                          <h2 className="card-title">Niall Horan</h2>
                          <p className="card-job">Web Developer</p>
                          <p className="card-text">
                            Lorem ipsum dolor sit amet, consectetur adipiscing
                            elit. In euismod ipsum et dui rhoncus auctor.
                          </p>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-4 col-md-6">
                      <div className="card">
                        <img
                          src="/Ellipse 325.png"
                          className="card-img-top"
                          alt="Card Image 3"
                        />
                        <div className="card-body">
                          <h2 className="card-title">Louis Tomlinson</h2>
                          <p className="card-job">Web Developer</p>
                          <p className="card-text">
                            Lorem ipsum dolor sit amet, consectetur adipiscing
                            elit. In euismod ipsum et dui rhoncus auctor.
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {/* Add more carousel items here */}
                <div className="carousel-item">
                  <div className="row">
                    <div className="col-lg-4 col-md-6">
                      <div className="card">
                        <img
                          src="/sa.jpg"
                          className="card-img-top"
                          alt="Card Image 4"
                        />
                        <div className="card-body">
                          <h2 className="card-title">John Doe</h2>
                          <p className="card-job">Frontend Developer</p>
                          <p className="card-text">
                            Lorem ipsum dolor sit amet, consectetur adipiscing
                            elit. In euismod ipsum et dui rhoncus auctor.
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <a
                className="carousel-control-prev"
                href="#myCarousel"
                role="button"
                data-slide="prev"
              >
                <i className="bi bi-arrow-left-circle-fill" />
              </a>
              <a
                className="carousel-control-next"
                href="#myCarousel"
                role="button"
                data-slide="next"
              >
                <i className="bi bi-arrow-right-circle-fill" />
              </a>
            </div>
          </div>
      </section>
      <section className="section5">
          <div className="container">
            <div className="box">
              <h1>
                Lorem ipsum <br />
                dolor sit amet
              </h1>
              <Link href={"/auth/login"}>
              <button className="btn btn-mulai">Mulai Dari Sekarang</button>
              </Link>
            </div>
          </div>
      </section>
      <Footer />
      <style>
        {`
              .section1 {
                height: 100vh;
                background-color:white;
              }
        
              .section1 .container {
                height: 100%;
              
              }
        
              .section1 .row {
                height: 100%;
                display: flex;
                align-items: center;
              }
        
              .section1 .text-container {
                height: 100%;
                display: flex;
                flex-direction: column;
                justify-content: center;
                font-size: 44px;
                width: 490px;
                max-width: 100%; 
                font-weight: 600;
                line-height: 70px;
              }
        
              .section1 .image-container {
                margin: 30px;
                position: relative;
              }
        
              .section1 .image-container img {
                position: relative;
                z-index: 2;
                width: 100%;
                height: 100%;
              }
        
              .section1 .background-overlay {
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background-color: #e2e5ed;
                transform: rotate(-15.79deg);
                position: absolute;
                z-index: 1;
              }
        
              .section1 .background-box1 {
                width: 118.59px;
                height: 118.59px;
                background-color: #5e50a1;
                position: absolute;
                bottom: -20px;
                left: -50px;
                z-index: 3;
              }
        
              .section1 .background-box2 {
                width: 46px;
                height: 46px;
                background-color: #fbb017;
                position: absolute;
                bottom: -40px;
                left: 40px;
                z-index: 3;
              }
        
              .section1 .background-box3 {
                position: absolute;
                bottom: 40px;
                left: 30px;
                z-index: 4;
              }
        
              .section2 {
                height: 100vh;
                background-color: white;
              }
        
              .section2 .container {
                height: 100%;
              }
        
              .section2 .row {
                height: 100%;
                display: flex;
              }
        
              .section2 .left-section {
                margin-top: 130px;
              }
        
              .section2 .right-section {
                margin-top: 140px;
              }
        
              .section2 .image-container {
                position: relative;
              }
        
              .section2 .image-container img {
                position: relative;
                z-index: 2;
                width: 100%;
                height: auto;
                display: block;
              }
        
              .section2 .background-overlay {
                top: 10px;
                left: -30px;
                width: 100%;
                height: 100%;
                background-color: #e2e5ed;
                transform: rotate(12.57deg);
                position: absolute;
                z-index: 1;
              }
        
              .section2 .background-box1 {
                width: 90px;
                height: 90px;
                background-color: #5e50a1;
                position: absolute;
                top: -40px;
                left: -30px;
                z-index: 3;
              }
        
              .section2 .icon-text {
                display: flex;
                align-items: center;
                font-weight: 400;
                font-size: 16px;
                margin-top: 34px;
              }
        
              .section2 .icon-text i {
                margin-right: 22px;
                color: #5e50a1;
                font-size: 24px;
              }
        
              .section3 {
                height: 100vh;
                background-color: white;
                padding: 50px 0;
              }
        
              .section3 .container {
                height: 100%;
              }
        
              .section3 .row {
                height: 100%;
                display: flex;
                flex-wrap: wrap;
                align-items: center;
              }
        
              .section3 .left-section {
                margin-top: 50px;
                padding-right: 20px;
              }
        
              .section3 .right-section {
                margin-top: 50px;
              }
        
              .section3 .image-container {
                position: relative;
              }
        
              .section3 .image-container img {
                position: relative;
                z-index: 2;
                width: 100%;
                height: auto;
                display: block;
              }
        
              .section3 .background-overlay {
                top: 10px;
                left: -10px;
                width: 100%;
                height: 100%;
                background-color: #e2e5ed;
                transform: rotate(-11.92deg);
                position: absolute;
                z-index: 1;
              }
        
              .section3 .background-box1 {
                width: 90px;
                height: 90px;
                background-color: #fbb017;
                position: absolute;
                top: -35px;
                right: -30px;
                z-index: 3;
              }
        
              .section3 .icon-text {
                display: flex;
                align-items: center;
                font-weight: 400;
                font-size: 16px;
                margin-bottom: 20px;
              }
        
              .section3 .icon-text i {
                margin-right: 10px;
                color: #fbb017;
                font-size: 24px;
              }
        
              .section3 .icon-text span {
                flex: 1;
              }
        
              .section4 {
                height: 100vh;
                background-color: whitesmoke;
              }
        
              .section4 .container {
                padding-top: 50px;
                padding-bottom: 75px;
              }
              .carousel-card {
                position: relative;
              }
              .card {
                width: 339px;
                height: 437px;
                align-items: center;
                text-align: center;
                padding-top: 26px;
              }
              .section4 img {
                width: 120px;
                height: 120px;
                border: 5px solid #fbb017;
                border-radius: 50%;
              }
        
              .carousel-control-prev,
              .carousel-control-next {
                position: absolute;
                top: 50%;
                transform: translateY(-50%);
                color: #5e50a1;
                font-size: 32px;
                opacity: 1;
              }
        
              .carousel-control-prev:hover,
              .carousel-control-next:hover {
                color: #5e50a1;
              }
        
              .carousel-control-prev {
                left: -80px;
              }
        
              .carousel-control-next {
                right: -80px;
              }
        
              .section5 {
                height: 60vh;
              }
        
              .section5 .box {
                background-color: #5e50a1;
                max-width: 1140px;
                width: 90%;
                height: 227px;
                border-radius: 40px 8px 40px 8px;
                display: flex;
                justify-content: space-between;
                align-items: center;
                position: relative;
                margin: 0 auto;
                padding: 0 20px;
              }
        
              .section5 .container {
                padding-top: 80px;
              }
        
              .section5 .box h1 {
                margin: 0;
                color: #ffffff;
                font-weight: 600;
                font-size: 36px;
                line-height: 56px;
              }
        
              .section5 .box .btn-mulai {
                background-color: white;
                color: #5e50a1;
                border: none;
                padding: 12px 24px;
                border-radius: 8px;
                font-size: 18px;
                cursor: pointer;
              }
        
              .btn-mulai {
                color: white;
                background-color: #5e50a1;
              }

              .btn-mulai:hover {
                color: white;
                background-color: #5e50a1;
              }

              @media (max-width: 767px) {
                .section1 .text-container {
                    width: 100%;
                    text-align: left;
                    font-size: 24px;
                    line-height: 36px;
                  }

                .section2 .row {
                  flex-direction: column;
                }
        
                .section2 .left-section {
                  margin-top: 20px;
                }
        
                .section2 .right-section {
                  margin-top: 10px;
                }
        
                .section2 .background-box1 {
                  display: none;
                }
        
                .section2 .background-overlay {
                  display: none;
                }
              }
        
              @media (max-width: 767px) {
          .section3 .row {
            flex-direction: column; 
          }
        
          .section3 .left-section {
            margin-top: 40px; 
            padding-right: 0; 
          }
        
          .section3 .right-section {
            margin-top: 20px; 
          }
        
          .section3 .background-box1 {
            display: none; 
          }
        
          .section3 .background-overlay {
            display: none; 
          }
        
          #section4 {
                display: none;
              }
        }
        @media (max-width: 768px) {
            .section5 .container{
                padding-top: 150px;
            }
          .section5 .box {
            flex-direction: column;
            height: auto;
            padding: 30px 20px;
            border-radius: 40px;
            text-align: center;
          }
    
          .section5 .box h1 {
            font-size: 28px;
            line-height: 36px;
            margin-bottom: 20px;
          }
        }
        `}
      </style>
    </>
  );
}

export default App;
